name: 'Add Header'
author: 'Psyvern'
description: 'Adds a header to specified files'
inputs:
    source:
        description: 'The file containing the header'
        required: true
        default: '.github/FILE_HEADER'
    filter:
        description: 'The filter specifying the files to target'
        required: true
        default: '*'
    prefix:
        description: 'The prefix for the inserted content'
        required: false
        default: ''
    suffix:
        description: 'The suffix for the inserted content'
        required: false
        default: ''
runs:
    using: 'node16'
    main: 'index.js'